// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type CovidUsaCasesByDate struct {
	LastUpdate          sql.NullTime
	Confirmed           sql.NullInt32
	Deaths              sql.NullInt32
	Recovered           sql.NullFloat64
	Active              sql.NullFloat64
	IncidentRate        sql.NullString
	PeopleTested        sql.NullFloat64
	PeopleHospitalized  sql.NullFloat64
	MortalityRate       sql.NullString
	Uid                 int64
	TestingRate         sql.NullString
	HospitalizationRate sql.NullString
	CreatedAt           time.Time
}

type CovidUsaLocation struct {
	Uid           int64
	Iso2          sql.NullString
	Iso3          sql.NullString
	Code3         sql.NullInt32
	Fips          sql.NullFloat64
	Admin2        sql.NullString
	ProvinceState sql.NullString
	CountryRegion sql.NullString
	Lat           sql.NullFloat64
	Long          sql.NullFloat64
	CombinedKey   sql.NullString
	Population    sql.NullInt64
}
